function fetchTO(url,ms){ms=ms||7000;const c=new AbortController();const t=setTimeout(function(){c.abort()},ms);return fetch(url,{signal:c.signal}).finally(function(){clearTimeout(t)})}
function walkRecipe(node){if(!node||typeof node!=='object')return null;var t=node['@type'];var is=t==='Recipe'||(Array.isArray(t)&&t.indexOf('Recipe')>=0);if(is)return node;if(Array.isArray(node['@graph'])){for(var i=0;i<node['@graph'].length;i++){var h=walkRecipe(node['@graph'][i]);if(h)return h}}if(Array.isArray(node)){for(var j=0;j<node.length;j++){var h2=walkRecipe(node[j]);if(h2)return h2}}return null}
function decodeHtml(t){return String(t).replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function ingsFromHtml(html){var out=[];html.replace(/itemprop=["']recipeIngredient["'][^>]*>([^<]+)/gi,function(_,x){x=decodeHtml(x);if(x&&x.length>2&&x.length<180)out.push(x);return _});return out.filter(function(v,i,a){return a.indexOf(v)===i})}
function recipeFromLd(rec,url){var img=rec.image;var image=typeof img==='string'?img:Array.isArray(img)?(img[0]&&(img[0].url||img[0])):img&&img.url;var inst=rec.recipeInstructions;var instructions=[];if(typeof inst==='string')instructions=[inst];else if(Array.isArray(inst))instructions=inst.map(function(x){return x.text||String(x)}).filter(Boolean);var ings=(rec.recipeIngredient||[]).map(String).map(decodeHtml).map(parseLine);return{id:Date.now(),title:String(rec.name||'Recipe').replace(/\s+/g,' ').trim(),sourceUrl:url,image:image||'',yield:rec.recipeYield!=null?String(rec.recipeYield):'',prepMin:isoMin(rec.prepTime),cookMin:isoMin(rec.cookTime),totalMin:isoMin(rec.totalTime)||((isoMin(rec.prepTime)||0)+(isoMin(rec.cookTime)||0))||null,ingredients:ings,instructions:instructions}}
function recipeFromLines(title,url,lines){var ings=lines.map(function(l){return l.replace(/^[-\u2022*\d.)\s]+/,'').trim()}).filter(function(l){return l.length>2}).map(parseLine);if(ings.length<2)throw new Error('Need at least 2 ingredient lines.');return{id:Date.now(),title:title||'Pasted recipe',sourceUrl:url||'',image:'',yield:'',prepMin:null,cookMin:null,totalMin:null,ingredients:ings,instructions:[]}}
async function fetchHtml(url,onStatus){var encoded=encodeURIComponent(url);var tries=['https://api.allorigins.win/get?url='+encoded,'https://corsproxy.io/?'+encoded,'https://api.allorigins.win/raw?url='+encoded,'https://api.codetabs.com/v1/proxy?quest='+encoded];if(onStatus)onStatus('Trying a few readers at once…');var jobs=tries.map(async function(u){var r=await fetchTO(u,7000);if(!r.ok)throw new Error('bad');var t=await r.text();if(t.trim().charAt(0)==='{'){try{var j=JSON.parse(t);if(j.contents)t=j.contents}catch(e){}}if(!t||t.length<300)throw new Error('empty');return t});try{return await Promise.any(jobs)}catch(e){throw new Error('Page readers timed out. Paste the ingredients below — that is instant.')}}
async function scrape(url,onStatus){var html=await fetchHtml(url,onStatus);if(onStatus)onStatus('Got the page. Pulling ingredients…');var scripts=html.match(/<script[^>]*type=["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/gi)||[];var rec=null;for(var i=0;i<scripts.length;i++){var raw=scripts[i].replace(/^<script[^>]*>/i,'').replace(/<\/script>$/i,'');try{rec=walkRecipe(JSON.parse(raw.trim()));if(rec)break}catch(e){}}if(rec){var r=recipeFromLd(rec,url);if(r.ingredients.length)return r}var fallback=ingsFromHtml(html);if(fallback.length>=2){var titleM=html.match(/<title[^>]*>([^<]+)/i);var title=titleM?titleM[1].replace(/\s*[|\-].*$/,'').trim():'Recipe';return recipeFromLines(title,url,fallback)}throw new Error('No recipe card on that site. Paste the ingredient list below.')}
function wireImport(){var box=document.getElementById('preview');if(!box)return;if(document.getElementById('paste'))return;var extra=document.createElement('div');extra.innerHTML='<p class="muted">If the page stalls, paste ingredients one per line.</p><textarea id="paste" rows="6" placeholder="1 cup flour\n2 eggs\n1/2 cup sugar"></textarea><button class="ghost gold" id="fromPaste">Use pasted ingredients</button>';box.parentNode.insertBefore(extra,box);document.getElementById('fromPaste').onclick=function(){var lines=document.getElementById('paste').value.split(/\n/).map(function(x){return x.trim()}).filter(Boolean);try{var r=recipeFromLines('Pasted recipe',(document.getElementById('url')||{}).value||'',lines);current=r;saveRecipes([r].concat(recipes()));showRecipe(r,true)}catch(e){box.innerHTML='<p class="muted">'+e.message+'</p>'}};var fetchBtn=document.getElementById('fetch');if(fetchBtn)fetchBtn.onclick=async function(){var url=(document.getElementById('url')||{}).value||'';url=url.trim();if(!url)return;box.innerHTML='<p class="muted">Opening the page…</p>';try{var r=await scrape(url,function(msg){box.innerHTML='<p class="muted">'+msg+'</p>'});current=r;saveRecipes([r].concat(recipes().filter(function(x){return x.sourceUrl!==url})));showRecipe(r,true)}catch(e){box.innerHTML='<p class="muted">'+e.message+'</p>'}}}
var _render=render;render=function(){_render();if(typeof view!=='undefined'&&view==='import')wireImport()};
